# Change these first
owner: furentes # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://furentes.de
  - name: TeamSpeak 3 Server
    check: "tcp-ping"
    url: 116.203.204.41
    port: 10011

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.furentes.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - Furentes.de
  introTitle: "**Furentes.de** Status Monitor"
  introMessage: Aktuelleste Status Informationen zu den [Furentes.de](https://furentes.de) Seiten und Servern.
  navbar:
    - title: Start
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
